name: Step 1, Create an issue

# This step triggers after the learner has created a new issue
# This step sets STEP to 2
# This step closes <details id=1> and opens <details id=2>

# This will run every time we create a new issue
# Reference https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  issues:
    types: [opened, edited]

# Reference https://docs.github.com/en/actions/security-guides/automatic-token-authentication
permissions:
  # Need `contents: read` to checkout the repository
  # Need `contents: write` to update the step metadata
  contents: write

jobs:
  on_create_an_issue:
    name: On create an issue

    # We will only run this action when:
    # 1. This repository isn't the template repository
    # 2. The event is an issue
    # 3. The issue name is 'chore: create contribution document'
    # Reference https://docs.github.com/en/actions/learn-github-actions/contexts
    # Reference https://docs.github.com/en/actions/learn-github-actions/expressions
    if: ${{ !github.event.repository.is_template && github.event.issue && contains(github.event.issue.title, 'create contribution document') }}

    # We'll run Ubuntu for performance instead of Mac or Windows
    runs-on: ubuntu-latest

    steps:
      # We'll need to check out the repository so that we can edit the README
      - name: Checkout
        uses: actions/checkout@v3.5.1
        with:
          fetch-depth: 0 # Let's get all the branches

      # Update README to close <details id=1> and open <details id=2>
      # and set STEP to '2'
      - name: Update to step 2
        uses: skills/action-update-step@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 1
          to_step: 2
